### PR TITLE
SJ-139: New .sql for ActualActivityForm

### PR DESCRIPTION
**Pull request by selbyheyman**
Changes
===

1. Drops old dbActualActivityForm if it exists
2. Drops old Attendees table if it exists
3. Creates new tables

### CODE REVIEW

**Review by jwilli39 — CHANGES_REQUESTED** [review]
Tried importing sql/16updateActualActivityForm but unfortunately am getting this error message, also for the name of the file I think you may have accidentally left out the .sql extension.  aScreenshot 2024-11-23 at 8 41 46 AM

**Review by jwilli39 — APPROVED** [review]
Everything looks good.

**Comment by selbyheyman** [comment]
> Everything looks good.

I had to edit some things since then, i needed to change the name of a column and remove the drop statements for the foreign keys (we still need those)

**Review by jwilli39 — CHANGES_REQUESTED** [review]
I think this line right here might cause an error:

CHANGE COLUMN `mealinfo` `meal_info` ENUM('meal_provided', 'meal_paid', 'no_meal') NOT NULL

I believe that the column name is already meal_info for that table, also the only other thing I think there might be a small syntax error with regards to the parentheses around the alter table block, but everything else should be good to go.

**Review by jwilli39 — CHANGES_REQUESTED** [review]
The only other thing is that on the main branch the 7actualActivityForm.sql already uses meal_info as opposed to mealinfo so might just have to switch up the syntax to modify column instead of change column.

Potential Solution:

ALTER TABLE `dbActualActivityForm`
MODIFY COLUMN `meal_info` ENUM('meal_provided', 'meal_paid', 'no_meal') NOT NULL;

**Comment by selbyheyman** [comment]
> I think this line right here might cause an error:
> 
> CHANGE COLUMN `mealinfo` `meal_info` ENUM('meal_provided', 'meal_paid', 'no_meal') NOT NULL
> 
> I believe that the column name is already meal_info for that table, also the only other thing I think there might be a small syntax error with regards to the parentheses around the alter table block, but everything else should be good to go.

Okay, I broke up the alter table statements. 

Also, on the siteground server, the 7actualActivity.sql file still has the column name as `mealinfo`, I was going off of that table when writing the alter statements. If this is wrong let me know!

**Review by jwilli39 — APPROVED** [review]
Whoops you're right just checked site ground the attribute is still mealinfo, everything should be good to go.

**Pull request merged**
