### PR TITLE
SJ-109 Staff Fill Angel Wish Gift Form

### PR DESCRIPTION
**Pull request by brogers1500**
Added functionality for staff to fill the angel wish gift form for a family

### CODE REVIEW

**Review by jwilli39 — CHANGES_REQUESTED** [review]
The only problem that I ran into when submitting the form from the staff account was that when I submitted the data with the auto populated phone number format (540) 456-7890 I got an 'out of range' error message, but when I manually edited the text box on the form to 5404567890 it was submitted successfully.

One quick potential solution could be if you update the sql table attribute from `phone` int(12) NOT NULL, to `phone` VARCHAR(15) NOT NULL this would allow for storing phone numbers with various formats like parentheses, dashes, or spaces and should resolve the out of range issue.

**Comment by brogers1500** [comment]
Altered the angel wish gift form table to change phone from int to varchar since it was causing errors for some people.

**Review by jwilli39 — CHANGES_REQUESTED** [review]
Hey real quick it's not that big of an issue but for the ALTER TABLE statement you accidentally misspelled the table name, if you could push the update for the sql/16updateAngelGiftPhone.sql file so that the name of the table being altered says dbAngelGiftForm as opposed to dbAngelgitGiftForm everything should be good to go.

**Comment by brogers1500** [comment]
I went ahead and deleted the new file altering the table and just changing the column in the angelWishGift.sql file while also adding a drop table statement at the top. Thought it would be better since there would be less sql files to deal with. You also wouldn't have to manually drop the table.

**Review by jwilli39 — APPROVED** [review]
Everything looks good.

**Pull request merged**
