### PR TITLE
Add dashboard item for adding children

### PR DESCRIPTION
**Pull request by itmacleod1995**
Pull request for assignment. Just adds the add child dashboard button to the family account dashboard page

### CODE REVIEW

**Comment by itmacleod1995** [comment]
&Test

**Review by aswann2 — APPROVED** [review]
Code is simple and outcome works as expected.

**Comment by jwilli39** [comment]
Looks good, every works as expected.

**Review by jwilli39 — APPROVED** [review]
Looks good, every works as expected.

**Pull request merged**
